#!/bin/bash

declare -g FILES="`git ls-tree HEAD env/ | cut -f 2`"
declare -g HOME_FILES="`git ls-tree HEAD env/ | cut -f 2 | sed 's,env,'"$HOME"','`"

declare -r WHITE='\E[37m'
declare -r GRAY='\E[38m'
declare -r BLUE='\E[34m'
declare -r CYAN='\E[36m'
declare -r YELLOW='\E[33m'
declare -r GREEN='\E[32m'
declare -r RED='\E[31m'
declare -r MAGENTA='\E[35m'

Print()
{
    echo "FILES: "
    echo "$FILES"
    echo " "
    echo "HOME_FILES:"
    echo "$HOME_FILES"
}

GetDependencies()
{
    declare -a DEPENDENCIES=("texlive"
			     "auctex"
			     "rosemacs-el")

    for (( i=0; i < ${#DEPENDENCIES[@]}; ++i ))
	do
	    which ${DEPENDENCIES[$i]}
	    if [ $? != 0 ]; then
		echo -e "${CYAN}Installing ${YELLOW}${DEPENDENCIES[$i]} ${CYAN}...${WHITE}"
		sudo apt-get install -y ${DEPENDENCIES[$i]}
	    fi
    done
}

Install()
{
    cp -r  $FILES $HOME/
}

Clean()
{
    rm -rf $HOME_FILES
}

ShowUsage()
{
    echo "Script for environment files"
    echo "Commands"
    echo "   -d|--depends    Install dependencies"
    echo "   -i|--install    Install environment files"
    echo "   -c|--clean      Clean environment files"
    echo "   -p|--print      Print variables"
    echo "   -h|--help       Show this help message"
}

main()
{
    case "$1" in
	'-d'|'--depends' )
	    GetDependencies
	;;

	'-i'|'--install' )
	    Install
	;;

	'-c'|'--clean' )
	    Clean
	;;

	'-p'|'--print' )
	    Print
	;;

	*)
	    ShowUsage
	    exit 1
	;;
    esac

    exit 0
}

main "$@"
